-- Wenyou default item catalog seed. Generated from docs/wenyou/item_catalog_draft_*.md.
CREATE TABLE IF NOT EXISTS item_catalog (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  rarity TEXT NOT NULL CHECK (rarity IN ('D', 'C', 'B', 'A', 'S')),
  item_type TEXT NOT NULL,
  category TEXT NOT NULL,
  effect_json TEXT NOT NULL,
  requirements_json TEXT NOT NULL DEFAULT '{}',
  use_cost_json TEXT NOT NULL DEFAULT '{}',
  tags_json TEXT NOT NULL DEFAULT '[]',
  era_tags_json TEXT NOT NULL DEFAULT '["universal"]',
  use_phase_json TEXT NOT NULL DEFAULT '[]',
  consume INTEGER NOT NULL DEFAULT 1,
  stackable INTEGER NOT NULL DEFAULT 0,
  shop_allowed INTEGER NOT NULL DEFAULT 0,
  gacha_allowed INTEGER NOT NULL DEFAULT 0,
  seal_rank TEXT,
  price INTEGER NOT NULL DEFAULT 0,
  weight INTEGER NOT NULL DEFAULT 100,
  enabled INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_item_catalog_shop ON item_catalog (shop_allowed, enabled, rarity);
CREATE INDEX IF NOT EXISTS idx_item_catalog_gacha ON item_catalog (gacha_allowed, enabled, rarity);
CREATE INDEX IF NOT EXISTS idx_item_catalog_category ON item_catalog (category, rarity);
CREATE INDEX IF NOT EXISTS idx_item_catalog_type ON item_catalog (item_type, rarity);

INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_001', '初级治愈药剂', 'D', 'consumable', '增益类', '{"text":"非战斗中恢复 30 HP；若处于 `轻伤`，额外让下一次 physical 行动惩罚 -1 降为 0；一次性","hp_restore":30}', '{}', '{}', '["增益","consumable"]', '["universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 30, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_002', '初级精神药剂', 'D', 'consumable', '增益类', '{"text":"恢复 30 SAN；若处于 `动摇`，额外移除 `动摇`；一次性","san_restore":30,"remove_conditions":["动摇"]}', '{}', '{}', '["增益","consumable"]', '["universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 30, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_003', '便利店透明胶', 'D', 'consumable', '工具类', '{"text":"临时固定一件轻小物体或封住一处细小缝隙，相关维修/封堵判定 +1；一次性"}', '{}', '{}', '["工具","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 22, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_004', '皱巴巴的课程表', 'D', 'consumable', '线索类', '{"text":"学校类副本中校验一次时间、教室或教师安排矛盾，成功时探索度 +1；一次性"}', '{}', '{}', '["线索","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 20, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_005', '少一颗螺丝的折叠椅', 'D', 'tool', '工具类', '{"text":"str_min 8；近战威慑/破坏 +1，对门窗、玻璃、简易隔板判定 +2；每次攻击耐久 -1，耐久 5","durability":5}', '{"str_min":8}', '{"durability":1}', '["工具","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 38, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_006', '洗衣粉量勺', 'D', 'tool', '探查类', '{"text":"对粉末、灰尘、药剂残留的观察判定 +1；可用 3 次，耐久 3","uses":3,"durability":3}', '{}', '{}', '["探查","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 26, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_007', '医院陪护腕带', 'D', 'tool', '伪装类', '{"text":"医院类副本中社交伪装 +1；被医护身份系统核验失败时暴露度 +1；耐久 4","durability":4}', '{}', '{"exposure":1}', '["伪装","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 34, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_008', '只剩一格电的充电宝', 'D', 'consumable', '增益类', '{"text":"让一件小型电子工具额外使用 1 次，或抵消一次低电量惩罚；一次性"}', '{}', '{}', '["增益","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 28, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_009', '物业通知单', 'D', 'consumable', '线索类', '{"text":"老小区/出租屋副本中校验一次门牌、停水、停电或维修时间矛盾；一次性"}', '{}', '{}', '["线索","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 20, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_010', '黏着头发的梳子', 'D', 'consumable', '探查类', '{"text":"对镜子、头发、浴室、梳妆台类异常观察 +2；使用后 SAN -2；一次性"}', '{}', '{"san":2}', '["探查","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 24, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_011', '旧校服外套', 'D', 'tool', '防护类', '{"text":"学校类副本中身份伪装 +1，抵消一次粉尘、泼水或轻微抓挠；耐久 6","durability":6}', '{}', '{}', '["防护","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 42, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_012', '过期润喉糖', 'D', 'consumable', '增益类', '{"text":"恢复 20 SAN，或让下一次呼喊/沟通/广播类行动判定 +1；一次性","san_restore":20}', '{}', '{}', '["增益","consumable"]', '["universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 24, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_013', '快递纸箱', 'D', 'tool', '伪装类', '{"text":"静止不动时藏匿判定 +1；移动时敏捷判定 -1；耐久 4","durability":4}', '{}', '{}', '["伪装","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 26, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_014', '发霉的毛巾', 'D', 'tool', '防护类', '{"text":"抵消一次烟雾、灰尘、低级气味污染；使用后社交伪装 -1，耐久 3","durability":3}', '{}', '{}', '["防护","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 24, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_015', '自动铅笔芯盒', 'D', 'consumable', '线索类', '{"text":"可在地图、门牌或纸面上标记 3 个线索点，线索被覆盖时保留一次提示；可用 3 次","uses":3}', '{}', '{}', '["线索","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 28, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_016', '超市购物篮', 'D', 'tool', '防护类', '{"text":"格挡一次轻微投掷物或小型实体扑咬，减伤 2；耐久 6","durability":6}', '{}', '{}', '["防护","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 38, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_017', '断齿塑料叉', 'D', 'tool', '工具类', '{"text":"agi_min 8；近身挣脱、割开软质封条判定 +1；对硬物无效，耐久 3","durability":3}', '{"agi_min":8}', '{}', '["工具","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 22, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_018', '空药瓶', 'D', 'consumable', '探查类', '{"text":"装取一次液体、粉末或气味样本，后续分析判定 +1；一次性"}', '{}', '{}', '["探查","consumable"]', '["universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 20, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_019', '没贴好的工牌', 'D', 'tool', '伪装类', '{"text":"办公室/商场/医院后勤区域身份伪装 +1；被仔细检查时暴露度 +1，耐久 5","durability":5}', '{}', '{"exposure":1}', '["伪装","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 36, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_020', '地下车库缴费单', 'D', 'consumable', '线索类', '{"text":"校验一次车辆、车位、进出时间或楼层矛盾；一次性"}', '{}', '{}', '["线索","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 20, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_021', '沾水的纸巾包', 'D', 'consumable', '增益类', '{"text":"移除一次轻微污渍、血迹或气味标记；若用于伪装，暴露度 -1；一次性"}', '{}', '{}', '["增益","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 24, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_022', '便携小镜子', 'D', 'tool', '探查类', '{"text":"观察拐角、背后或镜面异常判定 +1；镜类异常场景首次使用 SAN -2，耐久 5","durability":5}', '{}', '{"san":2}', '["探查","tool"]', '["universal"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 34, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_023', '退磁门禁卡', 'D', 'consumable', '工具类', '{"text":"低级门禁尝试刷开，成功率按工具判定 +1；失败时触发一次低级警报；一次性"}', '{}', '{}', '["工具","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 26, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_024', '掉漆保温杯', 'D', 'tool', '工具类', '{"text":"str_min 8；近战敲击 +1，也可装水/热液触发场景互动；耐久 6","durability":6}', '{"str_min":8}', '{}', '["工具","tool"]', '["universal"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 36, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_025', '半瓶花露水', 'D', 'consumable', '防护类', '{"text":"3 轮内对蚊虫、腐臭、轻微追踪气味抗性 +1；遇到火源时风险 +1；可用 2 次","uses":2}', '{}', '{}', '["防护","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 30, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_026', '失效的体温计', 'D', 'tool', '探查类', '{"text":"检测环境异常冷热或尸体温度矛盾判定 +1；耐久 4","durability":4}', '{}', '{}', '["探查","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 30, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_027', '便利店会员卡', 'D', 'special', '结算类', '{"text":"结算时若本副本发现过消费/店铺类线索，额外探索度 +1；每副本最多生效 1 次"}', '{}', '{}', '["结算","special"]', '["modern"]', '["settlement"]', 0, 0, 1, 1, NULL, 45, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_028', '倒着贴的门神贴纸', 'D', 'consumable', '防护类', '{"text":"贴在门/窗上后，1 轮内低级灵体进入判定 DC +1；使用后若门被打开则失效；一次性"}', '{}', '{}', '["防护","consumable"]', '["universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 32, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_029', '写错名字的请假条', 'D', 'consumable', '伪装类', '{"text":"学校/办公室副本中让一次缺席、迟到或离岗解释判定 +1；失败时暴露度 +1；一次性"}', '{}', '{"exposure":1}', '["伪装","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 24, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_030', '裂开的塑料脸盆', 'D', 'tool', '防护类', '{"text":"抵消一次泼洒、坠落小物或液体接触，减伤 1；也可盛水但每次使用耐久 -1，耐久 5","durability":5}', '{}', '{"durability":1}', '["防护","tool"]', '["universal"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 36, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_031', '一次性蓝色鞋套', 'D', 'consumable', '探查类', '{"text":"3 轮内行动不留下普通脚印，或追踪地面痕迹时判定 +1；一次性"}', '{}', '{}', '["探查","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 24, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_032', '晚点的公交票根', 'D', 'consumable', '规则类', '{"text":"验证一次“时间/路线/站点是否被副本轻微篡改”，只返回是/否/不完整；使用后 SAN -3；一次性"}', '{}', '{"san":3}', '["规则","consumable"]', '["universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 35, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_033', '基础止血贴', 'D', 'consumable', '增益类', '{"text":"非战斗中恢复 20 HP，并移除一次轻微流血标记；一次性","hp_restore":20}', '{}', '{}', '["增益","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 22, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_034', '薄荷味醒神贴', 'D', 'consumable', '增益类', '{"text":"恢复 20 SAN；3 轮内第一次抗困倦/催眠判定 +1；一次性","san_restore":20}', '{}', '{}', '["增益","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 26, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_035', '生锈螺丝刀', 'D', 'tool', '工具类', '{"text":"str_min 8；撬开小锁、拆卸螺丝、破坏薄板判定 +1；攻击失败时耐久额外 -1，耐久 5","durability":5}', '{"str_min":8}', '{}', '["工具","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 32, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_036', '办公室订书机', 'D', 'tool', '工具类', '{"text":"str_min 8；近战夹击/砸击 +1，也可临时固定纸张或布料；耐久 5","durability":5}', '{"str_min":8}', '{}', '["工具","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 32, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_037', '半卷警戒胶带', 'D', 'consumable', '防护类', '{"text":"封住一条普通通道或标记危险区域，1 轮内追逐/误入该区域 DC +1；可用 2 次","uses":2}', '{}', '{}', '["防护","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 30, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_038', '皱掉的挂号单', 'D', 'consumable', '线索类', '{"text":"医院类副本中校验一次科室、排队号、医生姓名或就诊时间矛盾；一次性"}', '{}', '{}', '["线索","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 20, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_039', '住户门禁扣', 'D', 'tool', '伪装类', '{"text":"老小区/公寓类副本中进入公共区域伪装 +1；被保安或门禁系统核验失败时暴露度 +1，耐久 4","durability":4}', '{}', '{"exposure":1}', '["伪装","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 34, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_040', '外卖保温袋', 'D', 'tool', '伪装类', '{"text":"以配送身份进入商场、写字楼、小区公共区判定 +1；携带显眼工具时该加成失效，耐久 5","durability":5}', '{}', '{}', '["伪装","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 34, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_041', '老式纽扣电池', 'D', 'consumable', '增益类', '{"text":"让一件小型探查类电子道具额外使用 1 次；若用于非探查电子设备，行动判定 +1 但失败时设备耐久 -1；一次性"}', '{}', '{"durability":1}', '["增益","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 26, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_042', '空白便利贴', 'D', 'consumable', '线索类', '{"text":"记录并固定一句 20 字以内的线索，3 轮内不会被普通记忆干扰覆盖；可用 3 次","uses":3}', '{}', '{}', '["线索","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 28, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_043', '反光安全背心', 'D', 'tool', '防护类', '{"text":"施工、停车场、仓库类副本中身份伪装 +1；黑暗环境被发现概率 +1，耐久 6","durability":6}', '{}', '{}', '["防护","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 40, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_044', '微波炉手套', 'D', 'tool', '防护类', '{"text":"抵消一次高温、烫伤或厨房类轻微伤害，减伤 2；潮湿时无效，耐久 4","durability":4}', '{}', '{}', '["防护","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 30, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_045', '口袋手账本', 'D', 'tool', '线索类', '{"text":"记录 5 条短线索；每副本 1 次，回看记录时记忆混乱判定 +1；耐久 6","durability":6}', '{}', '{}', '["线索","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 36, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_046', '拖把杆', 'D', 'tool', '工具类', '{"text":"str_min 8；近战推开、支撑、够取高处物体判定 +1；对潮湿地面异常判定 +2；耐久 6","durability":6}', '{"str_min":8}', '{}', '["工具","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 38, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_047', '破损雨伞', 'D', 'tool', '防护类', '{"text":"抵消一次雨水、坠落小物或液体泼洒；强风场景行动 DC +1，耐久 5","durability":5}', '{}', '{}', '["防护","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 34, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_048', '无声口哨', 'D', 'tool', '探查类', '{"text":"吹响后若附近有动物、儿童或听觉类异常，获得一次方向提示；使用后 SAN -1，耐久 3","durability":3}', '{}', '{"san":1}', '["探查","tool"]', '["universal"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 30, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_049', '半张值班表', 'D', 'consumable', '线索类', '{"text":"办公室、医院、学校副本中校验一次人员轮班、空岗或异常出勤；一次性"}', '{}', '{}', '["线索","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 20, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_050', '透明塑料文件袋', 'D', 'tool', '防护类', '{"text":"保护一张纸质线索不被水、血迹或普通污染损坏；可用 2 次，耐久 2","uses":2,"durability":2}', '{}', '{}', '["防护","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 26, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_051', '粗布止血包', 'D', 'consumable', '增益类', '{"text":"非战斗中恢复 25 HP，并移除一次轻微流血标记；一次性","hp_restore":25}', '{}', '{}', '["增益","consumable"]', '["ancient","universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 26, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_052', '安神香灰', 'D', 'consumable', '增益类', '{"text":"恢复 25 SAN；若在祠堂、寺观、义庄使用，额外让下一次恐惧判定 +1；一次性","san_restore":25}', '{}', '{}', '["增益","consumable"]', '["ancient"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 28, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_053', '客栈账本残页', 'D', 'consumable', '线索类', '{"text":"客栈/驿站副本中校验一次住客、房号、银钱或夜间出入矛盾；一次性"}', '{}', '{}', '["线索","consumable"]', '["ancient"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 20, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_054', '磨钝柴刀', 'D', 'tool', '工具类', '{"text":"str_min 8；砍断细绳、木栅、藤蔓判定 +1；对硬甲无效，耐久 6","durability":6}', '{"str_min":8}', '{}', '["工具","tool"]', '["ancient","universal"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 36, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_055', '破竹斗笠', 'D', 'tool', '防护类', '{"text":"抵消一次雨水、落灰或轻微头部擦伤；强风场景行动 DC +1，耐久 5","durability":5}', '{}', '{}', '["防护","tool"]', '["ancient"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 30, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_056', '褪色平安符', 'D', 'tool', '防护类', '{"text":"1 轮内低级灵体靠近判定 DC +1；触发后耐久 -1，耐久 2","durability":2}', '{}', '{"durability":1}', '["防护","tool"]', '["ancient","universal"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 34, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_057', '断裂算盘珠', 'D', 'consumable', '探查类', '{"text":"校验一次账目、数量、贡品或银钱记录矛盾；一次性"}', '{}', '{}', '["探查","consumable"]', '["ancient","republican"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 22, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_058', '半截红线', 'D', 'consumable', '规则类', '{"text":"标记一个门槛、床脚或井沿，验证一次“是否被低级空间规则轻微挪动”；使用后 SAN -3；一次性"}', '{}', '{"san":3}', '["规则","consumable"]', '["ancient","universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 35, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_059', '旧铜钱串', 'D', 'tool', '伪装类', '{"text":"市集、客栈、码头交易类社交伪装 +1；被仔细验看时暴露度 +1，耐久 4","durability":4}', '{}', '{"exposure":1}', '["伪装","tool"]', '["ancient","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 32, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_060', '义庄白布条', 'D', 'consumable', '探查类', '{"text":"检测尸身、棺木或停灵房中一次轻微移动痕迹；使用后 SAN -2；一次性"}', '{}', '{"san":2}', '["探查","consumable"]', '["ancient"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 24, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_061', '初级红药水', 'D', 'consumable', '增益类', '{"text":"非战斗中恢复 25 HP；若处于轻微擦伤或割伤，额外移除该轻微伤势标记；一次性","hp_restore":25}', '{}', '{}', '["增益","consumable"]', '["republican"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 28, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_062', '薄荷鼻烟', 'D', 'consumable', '增益类', '{"text":"恢复 25 SAN；3 轮内第一次抗困倦、迷香或催眠判定 +1；一次性","san_restore":25}', '{}', '{}', '["增益","consumable"]', '["republican"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 30, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_063', '报馆剪报', 'D', 'consumable', '线索类', '{"text":"校验一次新闻日期、人物姓名、码头事故或旧案时间线矛盾；一次性"}', '{}', '{}', '["线索","consumable"]', '["republican"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 22, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_064', '旧式钢笔', 'D', 'tool', '线索类', '{"text":"记录 5 条短线索；若线索涉及签名、字迹或契约，判定 +1；耐久 5","durability":5}', '{}', '{}', '["线索","tool"]', '["republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 34, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_065', '巡捕房袖章', 'D', 'tool', '伪装类', '{"text":"巡捕房、码头、街巷盘查场景社交伪装 +1；被正式警员核验失败时暴露度 +1，耐久 4","durability":4}', '{}', '{"exposure":1}', '["伪装","tool"]', '["republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 36, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_066', '戏票副券', 'D', 'consumable', '线索类', '{"text":"戏院/茶楼副本中校验一次座位、场次、演员或入场时间矛盾；一次性"}', '{}', '{}', '["线索","consumable"]', '["republican"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 20, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_067', '黄包车铜牌', 'D', 'tool', '工具类', '{"text":"街巷、码头、租界移动路线询问判定 +1；被车夫行会盘问失败时暴露度 +1，耐久 5","durability":5}', '{}', '{"exposure":1}', '["工具","tool"]', '["republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 32, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_068', '老照相馆底片', 'D', 'consumable', '探查类', '{"text":"显影一次照片、影子或镜中人数矛盾；使用后 SAN -2；一次性"}', '{}', '{"san":2}', '["探查","consumable"]', '["republican"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 28, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_069', '洋火柴盒', 'D', 'consumable', '工具类', '{"text":"点燃蜡烛、纸符或油灯，3 轮内黑暗观察惩罚 -1；潮湿时 50% 失效；可用 3 次","uses":3}', '{}', '{}', '["工具","consumable"]', '["republican","ancient"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 26, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_d_070', '药铺包药纸', 'D', 'consumable', '防护类', '{"text":"包裹一份粉末、药渣或小型证物，防止普通气味/湿气污染；一次性"}', '{}', '{}', '["防护","consumable"]', '["republican","ancient"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 22, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_001', '中级治愈药剂', 'C', 'consumable', '增益类', '{"text":"非战斗中恢复 60 HP，并移除 `轻伤`；一次性","hp_restore":60,"remove_conditions":["轻伤"]}', '{}', '{}', '["增益","consumable"]', '["universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 90, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_002', '中级精神药剂', 'C', 'consumable', '增益类', '{"text":"恢复 60 SAN，并移除 `动摇`；若在安全节点使用，额外恢复 `spi_current +1`，不超过上限；一次性","san_restore":60,"spi_restore":1,"remove_conditions":["动摇"]}', '{}', '{}', '["增益","consumable"]', '["universal"]', '["safe_node"]', 1, 1, 1, 1, NULL, 95, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_003', '清创绷带卷', 'C', 'consumable', '增益类', '{"text":"恢复 45 HP；可在非战斗中移除一次轻微流血或感染风险；可用 2 次","hp_restore":45,"uses":2}', '{}', '{}', '["增益","consumable"]', '["universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 100, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_004', '安神汤包', 'C', 'consumable', '增益类', '{"text":"恢复 50 SAN；3 轮内第一次恐惧、梦魇或迷香判定 +2；一次性","san_restore":50}', '{}', '{}', '["增益","consumable"]', '["ancient","republican"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 95, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_005', '再不睡就挂水袋', 'C', 'consumable', '增益类', '{"text":"移除 1 层疲劳，并恢复 25 HP；只能在安全节点或短休时使用；一次性","hp_restore":25}', '{"safe_node":true}', '{}', '["增益","consumable"]', '["modern","republican"]', '["safe_node"]', 1, 1, 1, 1, NULL, 90, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_006', '不知道谁批准的抗污染口服液', 'C', 'consumable', '增益类', '{"text":"3 轮内低级污染伤害 -3；若已经有轻度污染，额外让下一次污染判定 +2；一次性"}', '{}', '{}', '["增益","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 120, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_007', '写着“别慌”的稳定呼吸贴', 'C', 'consumable', '增益类', '{"text":"恢复 40 SAN；3 轮内第一次 `spi_current` 消耗减少 1，最低仍消耗 1；一次性","san_restore":40}', '{}', '{}', '["增益","consumable"]', '["modern","universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 110, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_008', '下雨也要上班的加厚雨披', 'C', 'tool', '防护类', '{"text":"抵消雨水、血迹、低级体液污染或酸性泼洒，减伤 4；遇到火源风险 +1，耐久 10","durability":10}', '{}', '{}', '["防护","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 130, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_009', '夹棉护身袄', 'C', 'tool', '防护类', '{"text":"寒冷、抓挠、跌撞类 HP 伤害 -4；潮湿后防护减半，耐久 10","durability":10}', '{}', '{}', '["防护","tool"]', '["ancient","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 125, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_010', '铁皮护心镜', 'C', 'tool', '防护类', '{"text":"抵消一次胸口、背后或飞来物轻中伤，减伤 5；耐久 8","durability":8}', '{}', '{}', '["防护","tool"]', '["ancient","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 145, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_011', '厚胶手套', 'C', 'tool', '防护类', '{"text":"接触电线、腐蚀液、血迹或污染物时判定 +2；每次接触耐久 -1，耐久 8","durability":8}', '{}', '{"durability":1}', '["防护","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 110, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_012', '黄符门帘', 'C', 'consumable', '防护类', '{"text":"贴在门、窗或床帐处，2 轮内低级灵体进入判定 DC +2；被强行撕开后失效；一次性"}', '{}', '{}', '["防护","consumable"]', '["ancient","universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 130, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_013', '护目风镜', 'C', 'tool', '防护类', '{"text":"烟尘、强光、飞溅液体造成的观察惩罚 -2；镜面异常首次触发时 SAN -5，耐久 7","durability":7}', '{}', '{"san":5}', '["防护","tool"]', '["modern","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 120, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_014', '旧式防毒面罩', 'C', 'tool', '防护类', '{"text":"毒雾、灰尘、腐臭环境 3 轮内行动惩罚 -2；使用后耐久 -1，耐久 6","durability":6}', '{}', '{"durability":1}', '["防护","tool"]', '["modern","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 150, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_015', '只录倒霉话的录音笔', 'C', 'tool', '线索类', '{"text":"保存一段 3 轮以内的声音线索，防止普通记忆干扰；电磁异常中使用失败率 +30%，耐久 6","durability":6}', '{}', '{}', '["线索","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 130, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_016', '拍完才多一个人的老照相机', 'C', 'tool', '线索类', '{"text":"拍下一处场景，后续校验人物、影子或门窗变化判定 +2；闪光会增加暴露度 +1，耐久 6","durability":6}', '{}', '{"exposure":1}', '["线索","tool"]', '["republican","modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 140, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_017', '账房暗格钥匙', 'C', 'consumable', '线索类', '{"text":"打开低级账房、柜台或暗格；若目标不是账目/信件类容器，判定只 +1；使用后 50% 损坏"}', '{}', '{}', '["线索","consumable"]', '["ancient","republican"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 100, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_018', '越看越像自己的失踪告示拓印', 'C', 'consumable', '线索类', '{"text":"校验一次失踪者姓名、照片、画像或时间线矛盾；成功时探索度 +2；使用后 SAN -3；一次性"}', '{}', '{"san":3}', '["线索","consumable"]', '["universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 95, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_019', '证物牛皮袋', 'C', 'tool', '线索类', '{"text":"保存 2 件小型证物，防止普通水渍、血迹或低级篡改污染；耐久 6","durability":6}', '{}', '{}', '["线索","tool"]', '["modern","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 120, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_020', '祠堂族谱残本', 'C', 'consumable', '线索类', '{"text":"校验一次亲属关系、祖先牌位、继承顺序或姓名禁忌；成功时获得一个家族线索标签；一次性"}', '{}', '{}', '["线索","consumable"]', '["ancient"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 110, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_021', '报馆排字盒', 'C', 'tool', '线索类', '{"text":"对报纸、印刷、错字、匿名信线索判定 +2；若暴露携带，社交伪装 -1，耐久 6","durability":6}', '{}', '{}', '["线索","tool"]', '["republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 120, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_022', '越怕越亮的低噪手电', 'C', 'tool', '探查类', '{"text":"黑暗观察惩罚 -2，异常源方向提示 +1；每轮使用耐久 -1，耐久 8","durability":8}', '{}', '{"durability":1}', '["探查","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 120, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_023', '铜铃探路串', 'C', 'tool', '探查类', '{"text":"经过门槛、井口、棺木、楼梯时，若存在低级空间异常获得一次提示；响动会暴露位置，耐久 6","durability":6}', '{}', '{}', '["探查","tool"]', '["ancient","universal"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 120, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_024', '罗盘裂针', 'C', 'tool', '探查类', '{"text":"定位一处阴气、磁场或方向异常，相关探查 +2；强污染区域首次使用 SAN -5，耐久 6","durability":6}', '{}', '{"san":5}', '["探查","tool"]', '["ancient","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 135, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_025', '巡夜煤油灯', 'C', 'tool', '探查类', '{"text":"3 轮内黑暗观察惩罚 -2，并能照出低级脚印/拖痕；遇风雨耐久额外 -1，耐久 7","durability":7}', '{}', '{}', '["探查","tool"]', '["ancient","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 125, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_026', '热成像贴片', 'C', 'consumable', '探查类', '{"text":"3 轮内检测活物、余温、隐藏管道或墙后热源判定 +2；低温异常场景效果减半；一次性"}', '{}', '{}', '["探查","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 115, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_027', '闹鬼频段收音机', 'C', 'tool', '探查类', '{"text":"接近广播、电话、电台、哭声类异常时获得方向提示；每次提示 SAN -3，耐久 6","durability":6}', '{}', '{"san":3}', '["探查","tool"]', '["modern","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 140, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_028', '消防斧', 'C', 'tool', '工具类', '{"text":"str_min 12；破门、砍断木板、威慑判定 +3；连续使用 2 次后疲劳 +1，耐久 10","durability":10}', '{"str_min":12}', '{"fatigue":1}', '["工具","tool"]', '["modern","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 155, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_029', '镖局短棍', 'C', 'tool', '工具类', '{"text":"str_min 10；近战压制、推开、格挡判定 +2；对灵体无效，耐久 10","durability":10}', '{"str_min":10}', '{}', '["工具","tool"]', '["ancient","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 125, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_030', '桃木短剑', 'C', 'tool', '工具类', '{"text":"spi_current_min 6；对低级灵体、纸人、影子类目标判定 +3；每次命中 SAN -2，耐久 7","durability":7}', '{"spi_current_min":6}', '{"san":2}', '["工具","tool"]', '["ancient","universal"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 150, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_031', '物业说打不开也赔的加固撬棍', 'C', 'tool', '工具类', '{"text":"str_min 10；开锁、撬门、拆卸栅栏判定 +3；失败时耐久额外 -1，耐久 9","durability":9}', '{"str_min":10}', '{}', '["工具","tool"]', '["modern","universal"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 135, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_032', '折叠工兵铲', 'C', 'tool', '工具类', '{"text":"str_min 10；挖掘、破土、清障、近战判定 +2；狭窄空间行动 DC +1，耐久 9","durability":9}', '{"str_min":10}', '{}', '["工具","tool"]', '["modern","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 140, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_033', '墨斗线', 'C', 'tool', '工具类', '{"text":"标记一条直线或门槛，2 轮内低级空间偏移判定 DC +2；使用后耐久 -1，耐久 5","durability":5}', '{}', '{"durability":1}', '["工具","tool"]', '["ancient","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 130, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_034', '领导还没签字的临时证件', 'C', 'consumable', '伪装类', '{"text":"3 轮内身份暴露度 -2；遇到 B 级以上身份系统时必须额外判定，失败暴露度 +2；一次性"}', '{}', '{"exposure":2}', '["伪装","consumable"]', '["modern","republican"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 130, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_035', '写错姓氏的旧公馆请柬', 'C', 'consumable', '伪装类', '{"text":"宴会、戏院、茶楼、公馆类场景入场判定 +2；被主人或管事核验失败时暴露度 +2；一次性"}', '{}', '{"exposure":2}', '["伪装","consumable"]', '["republican","ancient"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 120, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_036', '香客木牌', 'C', 'tool', '伪装类', '{"text":"寺观、祠堂、庙会类场景社交伪装 +2；对官府、军警场景无效，耐久 6","durability":6}', '{}', '{}', '["伪装","tool"]', '["ancient"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 115, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_037', '维修工马甲', 'C', 'tool', '伪装类', '{"text":"后勤、机房、电梯、地下车库场景伪装 +2；被要求出示工单时若无对应线索，暴露度 +1，耐久 8","durability":8}', '{}', '{"exposure":1}', '["伪装","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 130, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_038', '码头通行木牌', 'C', 'tool', '伪装类', '{"text":"码头、仓库、船坞场景通行判定 +2；被帮派或官差核验失败时暴露度 +2，耐久 5","durability":5}', '{}', '{"exposure":2}', '["伪装","tool"]', '["ancient","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 125, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_039', '祖宗说先凑合贴的镇物封条', 'C', 'consumable', '规则类', '{"text":"贴在门、柜、棺、镜之一上，1 轮内隔离一条低级规则触发；使用后 SAN -6，失败时威胁时钟 +1；一次性"}', '{}', '{"san":6,"threat_clock":1}', '["规则","consumable"]', '["universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 160, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_040', '听见规则咳嗽的听诊器', 'C', 'tool', '规则类', '{"text":"验证一条低级公开规则是否正在生效，只返回生效/未生效/不完整；每次使用 SAN -4，耐久 5","durability":5}', '{}', '{"san":4}', '["规则","tool"]', '["modern","universal"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 150, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_041', '染黑的铜镜', 'C', 'tool', '规则类', '{"text":"抵消一次低级镜面误认或倒影诱导；触发后耐久 -1，并 SAN -5，耐久 3","durability":3}', '{}', '{"san":5,"durability":1}', '["规则","tool"]', '["ancient","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 155, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_042', '楼上邻居拒不归还的绳梯', 'C', 'consumable', '位移类', '{"text":"从二层以内窗口、阳台、墙头移动到相邻安全节点，不能用于最终撤离；使用后疲劳 +1；一次性"}', '{}', '{"fatigue":1}', '["位移","consumable"]', '["modern","republican"]', '["safe_node"]', 1, 1, 1, 1, NULL, 140, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_043', '驿站换乘牌', 'C', 'consumable', '位移类', '{"text":"在驿站、码头、车站类节点中转到相邻公共节点；不能跳过主线封锁；一次性"}', '{}', '{}', '["位移","consumable"]', '["ancient","republican"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 135, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_044', '低级异常残片', 'C', 'material', '材料类', '{"text":"用于 C 级道具维护、D 级道具调校或低阶进化媒介合成；不可在副本内直接使用；可堆叠"}', '{}', '{}', '["材料","material"]', '["universal"]', '["hub","settlement"]', 0, 1, 1, 1, NULL, 100, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_c_045', '主神低阶回收券', 'C', 'special', '结算类', '{"text":"结算时将 1 件 D 级未损坏通用道具按 60% 估值回收为积分；每次结算最多使用 1 张"}', '{}', '{}', '["结算","special"]', '["universal"]', '["settlement"]', 0, 0, 1, 1, NULL, 120, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_001', '高级治愈药剂', 'B', 'consumable', '增益类', '{"text":"非战斗中恢复 100 HP，并移除 `重伤` 或 2 个轻微伤势标记；一次性","hp_restore":100,"remove_conditions":["重伤"]}', '{}', '{}', '["增益","consumable"]', '["universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 280, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_002', '高级精神药剂', 'B', 'consumable', '增益类', '{"text":"恢复 100 SAN，并移除 `恐慌` 或 `动摇`；若在安全节点使用，额外恢复 `spi_current +2`，不超过上限；一次性","san_restore":100,"spi_restore":2,"remove_conditions":["恐慌"]}', '{}', '{}', '["增益","consumable"]', '["universal"]', '["safe_node"]', 1, 1, 1, 1, NULL, 300, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_003', '创伤缝合包', 'B', 'consumable', '增益类', '{"text":"非战斗中恢复 80 HP，移除流血/骨裂/感染风险之一；使用后 2 轮敏捷判定 -1；一次性","hp_restore":80}', '{}', '{}', '["增益","consumable"]', '["modern","republican"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 260, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_004', '清心醒魂丸', 'B', 'consumable', '增益类', '{"text":"恢复 80 SAN；3 轮内第一次幻觉、迷香、梦魇或低级心智诱导判定 +3；一次性","san_restore":80}', '{}', '{}', '["增益","consumable"]', '["ancient","republican"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 285, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_005', '抗污染针剂', 'B', 'consumable', '增益类', '{"text":"移除 1 层轻度污染，或 4 轮内污染伤害 -6；使用后疲劳 +1；一次性"}', '{}', '{"fatigue":1}', '["增益","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 360, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_006', '肾上腺素加班贴', 'B', 'consumable', '增益类', '{"text":"3 轮内力量或敏捷相关行动 +3，结束后疲劳 +2 且 SAN -8；一次性"}', '{}', '{"san":8,"fatigue":2}', '["增益","consumable"]', '["modern","universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 320, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_007', '防爆透明盾', 'B', 'tool', '防护类', '{"text":"str_min 12；正面投掷物、冲撞、破片伤害 -8；连续格挡 2 次后行动 DC +1，耐久 12","durability":12}', '{"str_min":12}', '{}', '["防护","tool"]', '["modern","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 420, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_008', '租界防弹马甲', 'B', 'tool', '防护类', '{"text":"枪击、穿刺、碎片类 HP 伤害 -8；火焰/灵体伤害无效，耐久 10","durability":10}', '{}', '{}', '["防护","tool"]', '["modern","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 480, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_009', '铜钱护腕', 'B', 'tool', '防护类', '{"text":"低级诅咒、缠身、牵引类判定 +3；每次触发 SAN -3，耐久 8","durability":8}', '{}', '{"san":3}', '["防护","tool"]', '["ancient","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 360, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_010', '阴刻护心符', 'B', 'tool', '防护类', '{"text":"抵消一次心口、背刺、梦中惊醒造成的中等伤害，减伤 8；触发后污染 +2，耐久 3","durability":3}', '{}', '{"pollution":2}', '["防护","tool"]', '["ancient","universal"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 450, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_011', '抗污染雨衣', 'B', 'tool', '防护类', '{"text":"血雨、黑水、体液污染和低级酸蚀伤害 -6；遇火源或高温时伤害 +2，耐久 10","durability":10}', '{}', '{}', '["防护","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 390, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_012', '夜巡黑斗篷', 'B', 'tool', '防护类', '{"text":"夜间、雨巷、墓地、祠堂场景中潜行/躲藏 +3；正午或强光下无效，耐久 9","durability":9}', '{}', '{}', '["防护","tool"]', '["ancient","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 370, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_013', '异常热源镜', 'B', 'tool', '探查类', '{"text":"4 轮内检测活物、余温、墙后热源、伪装尸体判定 +3；低温异常场景首次使用 SAN -5，耐久 7","durability":7}', '{}', '{"san":5}', '["探查","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 340, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_014', '旧案胶片盒', 'B', 'tool', '线索类', '{"text":"保存 3 张场景影像，防止普通篡改；回看时可校验一次人物、影子、门窗或时间线矛盾 +3，耐久 6","durability":6}', '{}', '{}', '["线索","tool"]', '["republican","modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 380, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_015', '会自己排队的挂号单', 'B', 'consumable', '线索类', '{"text":"医院类或排队规则场景中，锁定一次真实顺序/科室/叫号矛盾；成功时探索度 +3；使用后 SAN -5；一次性"}', '{}', '{"san":5}', '["线索","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 300, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_016', '祖传罗盘裂盘版', 'B', 'tool', '探查类', '{"text":"定位一处中等阴气、空间偏移或方向异常，相关探查 +3；强污染区域使用污染 +2，耐久 6","durability":6}', '{}', '{"pollution":2}', '["探查","tool"]', '["ancient","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 400, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_017', '电梯监控备份盘', 'B', 'consumable', '线索类', '{"text":"校验一次电梯楼层、停靠时间、监控盲区或失踪者移动路径；成功时探索度 +3；一次性"}', '{}', '{}', '["线索","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 320, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_018', '县衙火签残套', 'B', 'consumable', '线索类', '{"text":"校验一次官府判词、牢房顺序、夜审时间或犯人姓名禁忌；失败时暴露度 +1；一次性"}', '{}', '{"exposure":1}', '["线索","consumable"]', '["ancient"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 300, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_019', '液压破门器', 'B', 'tool', '工具类', '{"text":"str_min 14；破门、顶开金属门、压制小型实体判定 +4；每次使用疲劳 +1，耐久 8","durability":8}', '{"str_min":14}', '{"fatigue":1}', '["工具","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 520, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_020', '镇魂桃木锤', 'B', 'tool', '工具类', '{"text":"spi_current_min 7；对低中级灵体、纸人、影子目标判定 +4；每次命中 SAN -4，耐久 8","durability":8}', '{"spi_current_min":7}', '{"san":4}', '["工具","tool"]', '["ancient","universal"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 500, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_021', '骨柄短刀', 'B', 'tool', '工具类', '{"text":"agi_min 12；近战挣脱、割断血线/发丝/软质封印 +3；每次攻击污染 +1，耐久 7","durability":7}', '{"agi_min":12}', '{"pollution":1}', '["工具","tool"]', '["ancient","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 460, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_022', '阴影钉枪', 'B', 'tool', '工具类', '{"text":"str_min 12；固定门板、影子边缘、移动家具或低级实体判定 +3；每次使用 SAN -3，耐久 7","durability":7}', '{"str_min":12}', '{"san":3}', '["工具","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 470, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_023', '镖局铁尺', 'B', 'tool', '工具类', '{"text":"str_min 12；近战格挡、缴械、压制判定 +3；对无形目标无效，耐久 11","durability":11}', '{"str_min":12}', '{}', '["工具","tool"]', '["ancient","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 350, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_024', '报馆铅字匣', 'B', 'tool', '工具类', '{"text":"对报纸、印刷、匿名信、错字规则判定 +3；可重排一句 20 字内的普通文本线索，耐久 6","durability":6}', '{}', '{}', '["工具","tool"]', '["republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 360, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_025', '临时调查员证', 'B', 'tool', '伪装类', '{"text":"警局、医院、学校、物业类场景身份伪装 +3；遇 B+ 身份系统核验失败时暴露度 +3，耐久 5","durability":5}', '{}', '{"exposure":3}', '["伪装","tool"]', '["modern","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 420, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_026', '旧戏班脸谱', 'B', 'tool', '伪装类', '{"text":"戏院、庙会、婚丧队伍场景伪装 +3；摘下后 1 轮社交伪装 -2，耐久 6","durability":6}', '{}', '{}', '["伪装","tool"]', '["ancient","republican"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 360, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_027', '空房东钥匙串', 'B', 'tool', '伪装类', '{"text":"公寓、出租屋、老小区公共房间进入判定 +3；若被真实住户撞见暴露度 +2，耐久 6","durability":6}', '{}', '{"exposure":2}', '["伪装","tool"]', '["modern"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 390, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_028', '断站公交卡', 'B', 'consumable', '位移类', '{"text":"在公交站、走廊、医院候诊区等公共节点移动到相邻公共节点；不能跳过主线封锁；使用后 SAN -5；一次性"}', '{}', '{"san":5}', '["位移","consumable"]', '["modern"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 430, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_029', '驿站夜行令', 'B', 'consumable', '位移类', '{"text":"在驿站、码头、城门、车站类节点中转到相邻安全或公共节点；失败时疲劳 +1；一次性"}', '{}', '{"fatigue":1}', '["位移","consumable"]', '["ancient","republican"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 420, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_030', '规则消毒湿巾', 'B', 'consumable', '规则类', '{"text":"擦除一个物体表面的低级污染标记或隔离一次低级触发条件；使用后 SAN -8，失败时威胁时钟 +1；一次性"}', '{}', '{"san":8,"threat_clock":1}', '["规则","consumable"]', '["modern","universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 560, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_031', '一次性停电许可', 'B', 'consumable', '规则类', '{"text":"让当前节点的照明/监控/广播类低级规则暂停 1 轮；不能影响核心规则；使用后 SAN -6、暴露度 +2；失败时威胁时钟 +1；一次性"}', '{}', '{"san":6,"threat_clock":1,"exposure":2}', '["规则","consumable"]', '["modern","republican"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 540, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_032', '低阶因果夹', 'B', 'tool', '规则类', '{"text":"夹住一张纸质线索或小型物品，2 轮内防止低级因果篡改；每轮 SAN -3，耐久 4","durability":4}', '{}', '{"san":3}', '["规则","tool"]', '["universal"]', '["instance","hub","settlement"]', 0, 0, 1, 1, NULL, 580, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_033', '镜后封条', 'B', 'consumable', '规则类', '{"text":"封住一面镜子、玻璃、黑水倒影的低级通道 2 轮；使用后污染 +3；一次性"}', '{}', '{"pollution":3}', '["规则","consumable"]', '["ancient","republican","universal"]', '["instance","hub","settlement"]', 1, 1, 1, 1, NULL, 560, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_034', '中级异常结晶', 'B', 'material', '材料类', '{"text":"用于 B 级道具维护、C 级道具调校、低阶进化媒介合成或 A 级物品解封材料；不可在副本内直接使用；可堆叠"}', '{}', '{}', '["材料","material"]', '["universal"]', '["hub","settlement"]', 0, 1, 1, 1, NULL, 340, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_b_035', '主神中阶回收券', 'B', 'special', '结算类', '{"text":"结算时将 1 件 C 级未损坏通用道具按 65% 估值回收为积分；每次结算最多使用 1 张"}', '{}', '{}', '["结算","special"]', '["universal"]', '["settlement"]', 0, 0, 1, 1, NULL, 360, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_001', '特级治愈药剂', 'A', 'consumable', '增益类', '{"text":"只能在安全节点或结算前休整使用；恢复至 HP 上限，并移除 1 个重伤状态；使用后疲劳 +2；一次性","hp_full":true}', '{"safe_node":true}', '{"fatigue":2}', '["增益","consumable"]', '["universal"]', '["safe_node"]', 1, 1, 0, 1, 'A', 900, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_002', '特级精神药剂', 'A', 'consumable', '增益类', '{"text":"只能在安全节点或主神空间使用；恢复至 SAN 上限，并恢复 `spi_current +3`，不超过上限；使用后 1 个副本内精神类恢复效果 -50%；一次性","san_full":true,"spi_restore":3}', '{"safe_node":true}', '{}', '["增益","consumable"]', '["universal"]', '["hub","safe_node"]', 1, 1, 0, 1, 'A', 950, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_003', '瞬时缝合胶囊', 'A', 'consumable', '增益类', '{"text":"受到致命 HP 伤害时可触发，保留 1 HP 并移除流血；触发后债务 +300、疲劳 +3、3 轮内行动 DC +2；一次性"}', '{}', '{"fatigue":3,"debt":300}', '["增益","consumable"]', '["modern","universal"]', '["instance","hub","settlement"]', 1, 1, 0, 1, 'A', 1300, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_004', '主神急救白名单', 'A', 'special', '增益类', '{"text":"仅 `settlement` 或安全节点可用；本局内一次濒死结算改为重伤存活，不改写失败结果；使用后奖励积分 -30%；一次性"}', '{}', '{}', '["增益","special"]', '["universal"]', '["settlement"]', 1, 0, 0, 1, 'A', 1500, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_005', '低完成撤离票', 'A', 'consumable', '位移类', '{"text":"在非 Boss 追逐且主线完成度至少 40% 时撤离到结算；结算评级最高只能到 B，债务 +500；一次性"}', '{}', '{"debt":500}', '["位移","consumable"]', '["universal"]', '["instance","hub","settlement"]', 1, 1, 0, 1, 'A', 1600, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_006', '复核用红笔', 'A', 'special', '结算类', '{"text":"结算时复核一次探索度、隐藏支线或特殊成就漏判；只能让一个评分项重算一次；使用后复核成功也要扣 10% 额外奖励；一次性"}', '{}', '{}', '["结算","special"]', '["modern","republican","universal"]', '["settlement"]', 1, 0, 0, 1, 'A', 1200, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_007', '规则改写橡皮', 'A', 'consumable', '规则类', '{"text":"擦掉一条低级公开规则中的 1 个非核心词，持续 2 轮；不能改写主线胜负条件；使用后 SAN -20、威胁时钟 +1；一次性"}', '{}', '{"san":20,"threat_clock":1}', '["规则","consumable"]', '["modern","universal"]', '["instance","hub","settlement"]', 1, 1, 0, 1, 'A', 1700, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_008', '替身工牌', 'A', 'tool', '防护类', '{"text":"受到一次直接致死攻击时，改为工牌损毁并承受 50% HP 上限伤害；触发后债务 +600，耐久 1","durability":1}', '{}', '{"debt":600}', '["防护","tool"]', '["modern","universal"]', '["instance","hub","settlement"]', 0, 0, 0, 1, 'A', 1800, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_009', '饿鬼胃袋', 'A', 'tool', '工具类', '{"text":"rank_min B、spi_current_min 10；吞噬一件小型污染物或低中级实体残片，相关压制判定 +5；使用后 SAN -18、污染 +6、冷却 2 轮，耐久 4","durability":4}', '{"rank_min":"B","spi_current_min":10}', '{"san":18,"pollution":6}', '["工具","tool"]', '["ancient","universal"]', '["instance","hub","settlement"]', 0, 0, 0, 1, 'A', 1550, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_010', '钟楼倒针表', 'A', 'tool', '规则类', '{"text":"将当前节点时间回拨 1 轮，只撤销位置和一次普通行动结果，不能撤销死亡/结算/核心规则；使用后威胁时钟 +1、SAN -15，耐久 2","durability":2}', '{}', '{"san":15,"threat_clock":1}', '["规则","tool"]', '["republican","modern"]', '["instance","hub","settlement"]', 0, 0, 0, 1, 'A', 1650, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_011', '无脸人面具', 'A', 'tool', '伪装类', '{"text":"5 轮内普通 NPC 记不住你的脸，社交伪装 +5；对 Boss、核心怪物和 B+ 身份系统无效；摘下面具后污染 +4，耐久 3","durability":3}', '{}', '{"pollution":4}', '["伪装","tool"]', '["modern","republican","universal"]', '["instance","hub","settlement"]', 0, 0, 0, 1, 'A', 1400, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_012', '禁病房床帘', 'A', 'tool', '防护类', '{"text":"在当前房间建立 2 轮临时安全节点，低中级实体进入 DC +5；不能用于 Boss 房或最终逃生节点；使用后耐久归零，耐久 1","durability":1}', '{}', '{}', '["防护","tool"]', '["modern"]', '["safe_node"]', 0, 0, 0, 1, 'A', 1500, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_013', '切线剪刀', 'A', 'tool', '位移类', '{"text":"agi_min 14、spi_current_min 9；剪断一条低中级追踪线、牵引线或路径锁定，移动到相邻安全节点；使用后 SAN -15，耐久 3","durability":3}', '{"agi_min":14,"spi_current_min":9}', '{"san":15}', '["位移","tool"]', '["universal"]', '["safe_node"]', 0, 0, 0, 1, 'A', 1450, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_014', '判官木牌', 'A', 'tool', '工具类', '{"text":"rank_min B、spi_current_min 10；对低中级灵体、伪装尸身、影子目标判定 +5；命中后目标 1 轮内追击 DC +3；每次使用 SAN -10，耐久 6","durability":6}', '{"rank_min":"B","spi_current_min":10}', '{"san":10}', '["工具","tool"]', '["ancient","republican"]', '["instance","hub","settlement"]', 0, 0, 0, 1, 'A', 1350, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_015', '遗忘相机', 'A', 'tool', '线索类', '{"text":"抹去一次自身暴露记录、监控影像或普通 NPC 目击记忆；成功后探索度 -3，且使用者遗忘一条非核心线索，耐久 2","durability":2}', '{}', '{}', '["线索","tool"]', '["modern","republican"]', '["instance","hub","settlement"]', 0, 0, 0, 1, 'A', 1250, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_016', '高级异常核心', 'A', 'material', '材料类', '{"text":"用于 A 级道具维护、B 级道具调校、A/S 级进化印记低阶解封材料；不可在副本内直接使用；可堆叠"}', '{}', '{}', '["材料","material"]', '["universal"]', '["hub","settlement"]', 0, 1, 0, 1, 'A', 1000, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_017', '主神高阶回收契约', 'A', 'special', '结算类', '{"text":"结算时将 1 件 B 级未损坏通用道具按 70% 估值回收为积分，或将 1 件 A 级道具按 55% 回收；每次结算最多使用 1 张"}', '{}', '{}', '["结算","special"]', '["universal"]', '["settlement"]', 0, 0, 0, 1, 'A', 1100, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_a_018', '半封口万能口袋', 'A', 'special', '彩蛋类', '{"text":"仅主神空间或安全节点可用；从 D/C/B 通用道具池随机取出 1 件临时道具，本副本结束后自动消失；每次使用债务 +200，冷却 1 个副本，可用 2 次","uses":2}', '{"hub_only":true}', '{"debt":200}', '["彩蛋","special"]', '["universal"]', '["hub","safe_node"]', 0, 0, 0, 1, 'A', 1800, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_s_001', '传说治愈原液', 'S', 'consumable', '增益类', '{"text":"seal_rank S；主神空间或安全节点使用，HP 与 SAN 恢复至上限，移除 2 个重伤/严重精神状态；若持有者低于 S 阶，只能恢复单项至 70%；使用后债务 +1000、下个副本初始威胁时钟 +1；一次性"}', '{}', '{"debt":1000,"threat_clock":1}', '["增益","consumable"]', '["universal"]', '["hub","safe_node"]', 1, 1, 0, 1, 'S', 12000, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_s_002', '蓝色次元口袋', 'S', 'special', '彩蛋类', '{"text":"seal_rank S；主神空间或安全节点使用，从 D-A 通用池指定一个功能标签后随机取 1 件道具；低于 S 阶只能取 D/C；每次使用债务 +500，连续使用追加污染 +5，冷却 1 个副本"}', '{}', '{"pollution":5,"debt":500}', '["彩蛋","special"]', '["universal"]', '["hub","safe_node"]', 0, 0, 0, 1, 'S', 18000, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_s_003', '邪神的心脏', 'S', 'tool', '规则类', '{"text":"seal_rank S、rank_min A、spi_min 18、spi_current_min 12、san_current_min 80；对规则实体、污染核心、血肉门判定 +6；使用后 SAN -35、污染 +12、威胁时钟 +1、冷却 3 轮，耐久 5","durability":5}', '{"rank_min":"A","spi_min":18,"spi_current_min":12}', '{"san":35,"pollution":12,"threat_clock":1}', '["规则","tool"]', '["ancient","universal"]', '["instance","hub","settlement"]', 0, 0, 0, 1, 'S', 22000, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_s_004', '主神客服转人工按钮', 'S', 'special', '规则类', '{"text":"seal_rank S；结算或主神空间使用，复核一次重大争议结算或异常扣债，只返回通过/驳回/需惩罚副本仲裁；低于 A 阶使用必定追加债务 +800；冷却 3 个副本，可用 2 次","uses":2}', '{}', '{"debt":800}', '["规则","special"]', '["universal"]', '["hub"]', 0, 0, 0, 1, 'S', 14000, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_s_005', '失败副本重开券', 'S', 'special', '结算类', '{"text":"seal_rank S；失败结算时可将死亡/团灭结果改为强制惩罚副本队列，保留 30% 已获探索奖励；使用后债务 +1500，且下次副本必须系统打工 NPC 模式；一次性"}', '{}', '{"debt":1500}', '["结算","special"]', '["universal"]', '["settlement"]', 1, 0, 0, 1, 'S', 20000, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_s_006', '死亡债务清零收据', 'S', 'special', '结算类', '{"text":"seal_rank S；主神空间使用，清除最多 3000 点死亡债务；若债务不足 3000，差额转为 1-3 个副本的奖励折扣；低于 A 阶使用追加污染 +10；一次性"}', '{}', '{"pollution":10}', '["结算","special"]', '["universal"]', '["hub"]', 1, 0, 0, 1, 'S', 12000, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_s_007', '空白世界门票', 'S', 'consumable', '位移类', '{"text":"seal_rank S；在主线完成度至少 60% 且非 Boss 最终压制中，转移到隐藏结局入口或特殊撤离节点；结算评级最高 A，威胁时钟 +2；一次性"}', '{}', '{"threat_clock":2}', '["位移","consumable"]', '["universal"]', '["instance","hub","settlement"]', 1, 1, 0, 1, 'S', 19000, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_s_008', '进化树禁果', 'S', 'material', '材料类', '{"text":"seal_rank S；用于一次 S 阶进化印记解封，或将一个未生效进化印记转化为同阶随机印记；低于 A 阶只能作为 A 级进化媒介使用；使用后污染 +15，且 1 个副本内 SAN 上限 -20；一次性"}', '{}', '{"pollution":15}', '["材料","material"]', '["universal"]', '["hub","settlement"]', 0, 1, 0, 1, 'S', 22000, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_s_009', '万用替身人偶', 'S', 'tool', '防护类', '{"text":"seal_rank S；抵消一次死亡、替换、献祭或身份抹除结算，改为保留 1 HP/1 SAN 并进入撤离倒计时；触发后债务 +2000、惩罚副本标记 +1，耐久 1","durability":1}', '{}', '{"debt":2000}', '["防护","tool"]', '["universal"]', '["instance","hub","settlement"]', 0, 0, 0, 1, 'S', 22000, 100, 1);
INSERT OR REPLACE INTO item_catalog (id, name, rarity, item_type, category, effect_json, requirements_json, use_cost_json, tags_json, era_tags_json, use_phase_json, consume, stackable, shop_allowed, gacha_allowed, seal_rank, price, weight, enabled) VALUES ('wy_s_010', '终局录像带', 'S', 'special', '线索类', '{"text":"seal_rank S；安全节点使用，揭示 Boss 或核心规则的一个真实弱点/禁忌/不可战胜条件；不会直接击败 Boss；使用后 SAN -40、污染 +8、探索度 +8；一次性"}', '{}', '{"san":40,"pollution":8}', '["线索","special"]', '["modern","republican","universal"]', '["safe_node"]', 1, 0, 0, 1, 'S', 16000, 100, 1);
